### ISSUE TITLE
ODT export error

### ISSUE THREAD

**Issue by Stikus** [saschaleib/dokuwiki-plugin-adhoctags#10]
Hello, I'm not sure if this issue belongs here or to [OPT plugin](https://github.com/lpaulsen93/dokuwiki-plugin-odt), but I'll start here.
I have test page with this code:
```
<pre><a [style=background-color:#fff200]>rm -rf %%__%%</a><a [style=background-color:#ea9999]>220130</a><a [style=background-color:#fff200]>*_fastq4%%__%%</a></pre>
```
![image](https://user-images.githubusercontent.com/41360525/232711384-b9dd92c5-3fe2-4204-af99-05d8df6cbd14.png)

All rendered good (I've updated our wiki and replaced pure HTML with this plugin), but [ODT](https://www.dokuwiki.org/plugin:odt) export not working on pages with plugin tags:

![image](https://user-images.githubusercontent.com/41360525/232710615-76f4a813-131b-48ee-8fd7-bbcee1b29616.png)

**Comment by saschaleib** [comment]
So there are actually people using ODT :-) Indeed, Ad-Hoc Tags doesn't support this export at the moment. But it should not be too hard to add at least rudimentary support... just give me a day or so :-)

**Comment by serge2016** [comment]
Yes, we do!
Thank you very much!

**Comment by Stikus** [comment]
I haven't found any other `.doc` or `.docx` export, that's why we use odt.
Thanks for plans of implementation this.

**Comment by saschaleib** [comment]
There is now rudimentary support for ODT export in the latest development build. 
* No more error message when exporting to ODT (hooray!) 
* Basic formatting for inline elements (e.g. `<i>` = italics, `<b>`= bold, etc.)
* block-level elements simply render as paragraphs for now. Exception: `<dt>`s are also bold.
* `<details>`/`<summary>` are always _opened_ in export.
* Unfortunately, `<h1>`... `<h6>` are also rendered as simple paragraphs. This may be a bit harder to fix, as this issue is related to the fundamental way how DokuWiki handles headlines (this is also the reason why you can't have text formatting in DokuWiki headlines, and why HTML headlines are not appearing in the TOC). I'm looking for a workaround, but that may not be so easy...

As always: this is still under development and might not yet always work as intended. Feedback is very much welcome! :-)

**Comment by serge2016** [comment]
Dear @saschaleib, could you add support for colors in the `<a>` elements for the example in this issue? I don't see corresponding changes in the last commit(

**Comment by saschaleib** [comment]
@serge2016 Ah, yes, sorry, forgot about that one. I'll have a look...

**Comment by saschaleib** [comment]
Hm, actually, links have the same problem as headlines... I have, for now, just added the link in front of the text (with an extra '#' character as link text). This is not a very good solution, I know. I'll still look into this - most likely together with the headlines, as the problem is more or less the same.

**Comment by serge2016** [comment]
Thank you!

**Comment by saschaleib** [comment]
So, I found a theoretical way to solve the link and headlines issues, but unfortunately it is blocked because of a bug in the ODT plugin. I have filed a report over there, and I keep this issue open to revisit it later, but this seems to be all I can do for now.

**Comment by Stikus** [comment]
Thanks for work, I assume you are talking about this issue: https://github.com/lpaulsen93/dokuwiki-plugin-odt/issues/289 - I left like there.

Do you plan to release a new version of the plugin with current changes, or you want to wait for a fix? For now, ODT export is broken due to missing of new release.

**Comment by saschaleib** [comment]
I would still like to make a few more tests to make sure that this doesn't have any other side-effects, but I guess I can make a new release either later today or maybe tomorrow. In the meantime, you can install directly from the main page (either download as ZIP, or just copy the URL of the ZIP file and use that for a manual update (don't forget to check "Override existing files", otherwise DokuWiki will add this as a new plugin).
